name: Java CI

on:
  push:
    branches: ["Pakjira"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
        fetch-depth: ${{ env.PR_FETCH_DEPTH }}

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '17.0.8.1' # Change this to the version you want

    - name: Compile Java
      run: |
        cd Pakjira/HolidayTravelVehicles 
        javac -d . *.java
      # Compile Java files from directory
